### ISSUE TITLE
503 service unavailable issue on executing the function app

### ISSUE THREAD

**Issue by MalateshPatil** [joseftw/jos.files#4]
I have deployed this function app to azure function app with Function premium plan as well as with App service plan. After we ran in azure portal I am getting 503 service unavailable issue. 

![image](https://user-images.githubusercontent.com/18049257/204718520-b4efc151-370f-4f7b-88b4-a25c802100bb.png)

![image](https://user-images.githubusercontent.com/18049257/204718596-b936848f-909f-40e0-be31-d25d820ce669.png)

But after 2-3 min  file uploads in the destination folder (zip files) in container.
 
![image](https://user-images.githubusercontent.com/18049257/204718651-feb4fe88-b7aa-491c-83c4-09a681d22ce1.png)

**Comment by joseftw** [comment]
Hello
Strange, I haven't seen this and my app has been running for a couple of years now...
Maybe open a azure support ticket?

**Comment by MalateshPatil** [comment]
Can you please let me know where you will be running your app?
